name: Run CMake Format
description: Runs CMake formatting and linting tools.
inputs:
  command:
    description: "The command to run. Possible values are 'format' or 'lint'. 'format' will run cmake-format, 'lint' will run cmake-lint."
    required: true
  path:
    description: The path to the project directory to format or lint. CMake files will be searched recursively in this directory.
    required: true
  apply-formatting:
    description: "Whether to apply formatting changes. Possible values are 'true' or 'false'. Only relevant for the 'format' command."
    required: false
    default: 'false'
  lint-log-level:
    description: "The log level for cmake-lint. Possible values are 'debug', 'info', 'warning', or 'error'. Only relevant for the 'lint' command."
    required: false
    default: warning
runs:
  using: docker
  image: Dockerfile
  entrypoint: python
  args:
    - github_action_entrypoint.py
    - ${{ inputs.command }}
    - ${{ inputs.path }}
    - ${{ inputs.apply-formatting }}
    - ${{ inputs.lint-log-level }}
